[package]
name = "meu_servidor_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["json"] }

# Framework web assíncrono
axum = "0.7"

# Executável assíncrono (runtime)
tokio = { version = "1.0", features = ["full"] }

# Para ler e enviar JSON (a feature "derive" é obrigatória)
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Para servir sua pasta de arquivos estáticos (HTML/CSS/JS)
tower-http = { version = "0.5", features = ["fs"] }
dotenvy = "0.15"